apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebox-deployment
  labels:
    name: phonebox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      server: phonebox_web
  strategy:
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        server: phonebox_web
    spec:
      containers:
      - name: phonebox-web
        image: thuan324/jobbee_server:phonebox
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.1"
          limits:
            memory: "100Mi"
            cpu: "0.15"
        ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: regcred
